# Core configuration (type 'conan config list' to list possible values)
core.package_id:default_build_mode=full_version_mode
core.package_id:default_embed_mode=full_version_mode
core.package_id:default_non_embed_mode=full_version_mode
core.package_id:default_python_mode=full_version_mode
core.package_id:default_unknown_mode=full_version_mode
